import { createClient } from '@supabase/supabase-js';

// Get environment variables
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate environment variables
if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error(
    'Missing Supabase environment variables. Please check your .env.local file.'
  );
}

// Create Supabase client
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Database types (will be auto-generated by Supabase later)
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          name: string;
          role: 'admin' | 'member';
          created_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          name: string;
          role: 'admin' | 'member';
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string;
          role?: 'admin' | 'member';
          created_at?: string;
        };
      };
      books: {
        Row: {
          id: string;
          title: string;
          author: string;
          isbn: string;
          publish_year: number;
          type: 'physical' | 'ebook';
          category: string;
          location: string | null;
          file_url: string | null;
          file_type: 'pdf' | 'epub' | null;
          stock: number;
          available_stock: number;
          qr_code: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          author: string;
          isbn: string;
          publish_year: number;
          type: 'physical' | 'ebook';
          category: string;
          location?: string | null;
          file_url?: string | null;
          file_type?: 'pdf' | 'epub' | null;
          stock?: number;
          available_stock?: number;
          qr_code?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          author?: string;
          isbn?: string;
          publish_year?: number;
          type?: 'physical' | 'ebook';
          category?: string;
          location?: string | null;
          file_url?: string | null;
          file_type?: 'pdf' | 'epub' | null;
          stock?: number;
          available_stock?: number;
          qr_code?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      transactions: {
        Row: {
          id: string;
          user_id: string;
          book_id: string;
          borrow_date: string;
          due_date: string;
          return_date: string | null;
          status: 'borrowed' | 'returned' | 'overdue';
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          book_id: string;
          borrow_date?: string;
          due_date: string;
          return_date?: string | null;
          status: 'borrowed' | 'returned' | 'overdue';
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          book_id?: string;
          borrow_date?: string;
          due_date?: string;
          return_date?: string | null;
          status?: 'borrowed' | 'returned' | 'overdue';
          created_at?: string;
        };
      };
      reading_progress: {
        Row: {
          id: string;
          user_id: string;
          book_id: string;
          current_page: number;
          total_pages: number | null;
          last_read_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          book_id: string;
          current_page?: number;
          total_pages?: number | null;
          last_read_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          book_id?: string;
          current_page?: number;
          total_pages?: number | null;
          last_read_at?: string;
        };
      };
    };
  };
};
